version: '3.9'
services:
  web:
    build: .
    container_name: web
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    environment:
      - DB_HOST=db

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - 80:80
    depends_on:
      - web
    restart: unless-stopped

  db:
    image: mysql
    container_name: db
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=names_db
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 2s
      timeout: 20s
      retries: 10
    restart: unless-stopped
